### ISSUE TITLE
ledgerblue.checkGenuine() fails at `data = loader.encryptAES(data)` with ValueError: Input strings must be a multiple of 16 in length

### ISSUE THREAD

**Issue by deo1** [LedgerHQ/blue-loader-python#11]
After following the instructions found here (under step 2): https://ledger.groovehq.com/knowledge_base/topics/how-to-verify-the-security-integrity-of-my-nano-s

I get the following failure.

(Windows 10 - python 3.5.4 - ledger nano s - secure element 1.3.1 - mcu 1.0)

PS C:\Users\Jesse\Documents\GitHub> `python -m ledgerblue.checkGenuine --targetId 0x31100002`
Traceback (most recent call last):
  File "C:\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Anaconda3\lib\runpy.py", line 85, in _run_code
    `exec(code, run_globals)`
  File "C:\Anaconda3\lib\site-packages\ledgerblue\checkGenuine.py", line 135, in <module>
    `data = loader.encryptAES(data)`
  File "C:\Anaconda3\lib\site-packages\ledgerblue\hexLoader.py", line 95, in encryptAES
    `encryptedData = cipher.encrypt(str(paddedData))`
  File "C:\Anaconda3\lib\site-packages\Crypto\Cipher\blockalgo.py", line 244, in encrypt
    `return self._cipher.encrypt(plaintext)`
**ValueError: Input strings must be a multiple of 16 in length**

**Comment by btchip** [comment]
Use Python 2 for the time being. The Python 3 compatible version will be available shortly

**Comment by deo1** [comment]
Thanks. Instructions in case it helps anyone else (if you installed the anaconda package).

get visual studio compiler from here: http://aka.ms/vcpython27
`conda create --name py27 python=2.7`
`activate py27`
`pip install --no-cache-dir ledgerblue`
`python -m ledgerblue.checkGenuine --targetId 0x31100002` (for nano s)

Feel free to close the issue if you're tracking py3 work some other way.
