### ISSUE TITLE
Loading firmware fails

### ISSUE THREAD

**Issue by chrisrico** [LedgerHQ/blue-loader-python#2]
I'm on MacOS. I got my virtualenv set up, python-loader installed, and the Ledger connected (I did have to use a new USB cable) in bootloader mode. When running the specified command, nothing happens for about 60 seconds, then the command fails and the Ledger Blue shuts off. Here is the log.

```
(ledger-blue) Chriss-MBP:bluer1 chrisrico$ python -m ledgerblue.runScript --fileName stm32l476_seproxyhal.patch_apdu 
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/chrisrico/.virtualenvs/ledger-blue/lib/python2.7/site-packages/ledgerblue/runScript.py", line 39, in <module>
    dongle.exchange(bytearray(data))	
  File "/Users/chrisrico/.virtualenvs/ledger-blue/lib/python2.7/site-packages/ledgerblue/comm.py", line 82, in exchange
    result = self.waitImpl.waitFirstResponse(timeout)
  File "/Users/chrisrico/.virtualenvs/ledger-blue/lib/python2.7/site-packages/ledgerblue/comm.py", line 126, in waitFirstResponse
    data = self.device.read(65)
  File "hid.pyx", line 122, in hid.device.read (hid.c:2546)
IOError: read error
```

**Comment by btchip** [comment]
Hi 

3 things to check 

- Have you verified you can load a regular application with this cable first ? 

- Are you sure you're in bootloader mode, and not in secure bootloader mode (you have to keep the button pushed until it displays "bootloader" at the bottom, the release it)

- Can you modify the Makefile to add --apdu to the command and see if there are additional logs posted ? 

Thanks

**Comment by chrisrico** [comment]
- I have not. I thought I needed to load a firmware first.
- Yes. I see "BOOTLOADER MODE No loaded firmware"
- I'm not sure to which command you're referring. I was trying to load the firmware from blue-nonsecure-firmware-releases.

**Comment by btchip** [comment]
Ok, so please try 1/ first, there might be a connectivity issue with the cable. In that case, you can cut the cable a bit (or we can send you one), or use it outside of the case. You don't need to load a firmware to start the samples. 

Sorry, I thought the command was in the Makefile but it isn't. In that, case, that would be 

``
python -m ledgerblue.runScript --apdu --fileName stm32l476_seproxyhal.patch_apdu
``

**Comment by chrisrico** [comment]
Ok, I took the Blue out of the case and the supplied cable is working now. I'm still getting the same error.

Here's a [log](https://github.com/LedgerHQ/blue-loader-python/files/222807/runScript.txt) of the output of the command using the --apdu flag.

**Comment by btchip** [comment]
ok, so everything is fine, it's loaded and turns off, but doesn't get a response on the last command so you see this error - we should catch it and display something less frightening. 

If you reboot, you'll see that it displays a "wipe" warning - which does nothing, since the onboarding is not there yet, but just in case you want to get rid of it, you can reflash the official signed release at https://github.com/LedgerHQ/blue-nonsecure-firmware-releases

Thanks for reporting that, even on a Sunday :)
