### ISSUE TITLE
no dongle found error

### ISSUE THREAD

**Issue by cardoe** [LedgerHQ/blue-loader-python#23]
I'm attempting to verify my new Ledger Nano S per https://ledger.zendesk.com/hc/en-us/articles/115005321449-How-to-verify-the-security-integrity-of-my-Nano-S- on Mac OS X 10.13.2 and after getting past the pycrypto issue in #22 I am still unable to verify it. Here's the output:

```
$ python -m ledgerblue.checkGenuine --targetId 0x31100002                 1 ↵
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/cardoe/work/blue-loader-python/ledgerblue/checkGenuine.py", line 127, in <module>
    dongle = getDongle(args.apdu)
  File "/Users/cardoe/work/blue-loader-python/ledgerblue/comm.py", line 212, in getDongle
    raise CommException("No dongle found")
ledgerblue.commException.CommException: Exception : No dongle found
```

**Comment by nheinrich** [comment]
Plug your ledger in.

**Comment by riordant** [comment]
I am experiencing this same issue after upgrading this package to 17 and Nano S to version 1.4.1. The new target ID is also being supplied. Also on MacOS

**Comment by nathanielcook** [comment]
Not documented anywhere, but it turns out the device must be configured before it will be found. If that doesn't work, try a different cable.

**Comment by zwarbo** [comment]
Just wanted to say thanks for this info. I didn't realise that the supplied Ledger USB cable was required. Once I saw this post I went back to using the supplied cable and it all worked again.

**Comment by TamtamHero** [comment]
Ledger USB cable is not required at all !
Actually, the one provided with nano S was of very bad quality (we upgraded the one furnished with Nano X, not sure about new nano S batches), so using another cable is often a fix to random issues.
