### ISSUE TITLE
"ledgerblue.commException.CommException: Exception : No dongle found"

### ISSUE THREAD

**Issue by riordant** [LedgerHQ/blue-loader-python#33]
OS: MacOS Sierra 10.12.5
device: Ledger Nano S
firmware: 1.4.1
Script: Any
Python: Either 2.7 or 3 - same results.
command: `python -m ledgerblue.checkGenuine --targetId 0x31100003`
Version:  `0.1.17` (commit `01ac90675898c14c5d2b1cef379cfdcc5774fe4f ` - ie. non pip version)
trace (for checkGenuine.py - but replace for any script):
```
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/tadhgriordan/Documents/blue-loader-python/ledgerblue/checkGenuine.py", line 137, in <module>
    dongle = getDongle(args.apdu)
  File "/Users/tadhgriordan/Documents/blue-loader-python/ledgerblue/comm.py", line 221, in getDongle
    raise CommException("No dongle found")
ledgerblue.commException.CommException: Exception : No dongle found
```

Ledger is recognised by my machine for all Apps, Ledger Manager, MyEtherWallet etc.
running `system_profiler SPUSBDataType`:
```
Nano S:

     Product ID: 0x0001
     Vendor ID: 0x2c97
     Version: 2.00
     Serial Number: 0001
     Speed: Up to 12 Mb/sec
     Manufacturer: Ledger
     Location ID: 0x14400000 / 8
     Current Available (mA): 500
     Current Required (mA): 100
     Extra Operating Current (mA): 0
```

I have another Nano S on 1.3 which works as normal.

**Comment by burin** [comment]
I get the same thing, but on MacOS 10.12.6, using the commit `01ac90675898c14c5d2b1cef379cfdcc5774fe4f` as well.

When using the `0.1.16` from pip, I get "Product is NOT genuine", same issue as described by this reddit user:

> I just received a my Ledger Nano S, updated to 1.4.1 and tested it using:
https://support.ledgerwallet.com/hc/en-us/articles/115005321449-How-to-verify-the-security-integrity-of-my-Nano-S-
> and it is returning 'Product is NOT genuine.' I was wondering if anyone else is getting this?

https://www.reddit.com/r/ledgerwallet/comments/82rfb8/new_ledger_nano_s_returning_product_is_not_genuine/

**Comment by riordant** [comment]
Yes, experiencing the exact same on 0.1.16.

**Comment by burin** [comment]
@riordant does `0.1.16` work fine on your `1.3` ledger? 

I recently got mine and updated to `1.4.1` immediately. I ran these scripts only after updating and never had `1.3` or other hardware to test.

**Comment by riordant** [comment]
Yes it does. If you are concerned with the authenticity of the device try and install a VM and run Ubuntu 16.04.

**Comment by burin** [comment]
Fixed in latest master

**Comment by riordant** [comment]
Working for all scripts bar loadApp (sigh). Closing this as fixed.
