### ISSUE TITLE
No dongle found

### ISSUE THREAD

**Issue by MathiasKandelborg** [LedgerHQ/blue-loader-python#46]
Hi, after installing and running the software in a virtualenv because of issues with hidapi (I just tried without first, but oh well), I still have problems!

I'll try a sixth restart and installing with a third separate virtualenv - my guess is that i still have something wrong on my side. Here's the stacktrace I get after running `python -m ledgerblue.checkGenuine --targetId 0x31100003` on the following hardware:
Ubuntu 18.04 with latest updates
ZSH terminal
Latest python 3
(sorry for the bad software, I'm not in the mood to spendd more time on that kind of stuff, since my basic installations are probably fine)

`Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/mathias/ledger/lib/python3.6/site-packages/ledgerblue/checkGenuine.py", line 137, in <module>
    dongle = getDongle(args.apdu)
  File "/home/mathias/ledger/lib/python3.6/site-packages/ledgerblue/comm.py", line 226, in getDongle
    raise CommException("No dongle found")
ledgerblue.commException.CommException: Exception : No dongle found`

**Comment by jleni** [comment]
In Linux you need to update your udev rules.. Maybe that step is missing?
You can find some info here:
https://support.ledgerwallet.com/hc/en-us/articles/115005165269-Connection-issues-with-Windows-or-Linux

**Comment by TamtamHero** [comment]
Additionally, no other program talking to the device should be opened at the moment you execute this command. 
Verify that no wallet is currently opened on your computer and try again.

**Comment by MathiasKandelborg** [comment]
I'm sorry for not updating, I've been in a rush lately. I fixed it by updating my udev rules. I'd missed that part.

Thanks for the info and also the great application!
