### ISSUE TITLE
loadApp fails because no targetVersion? 

### ISSUE THREAD

**Issue by mattspaeth** [LedgerHQ/blue-loader-python#55]
When running loadApp, it fails on installing to Ledger Nano S running firmware 1.55.

Command: 
`python -m ledgerblue.loadApp --appFlags 0x40 --apdu --tlv --targetId 0x31100004 --delete --fileName app.hex --appName "Ravencoin" --appVersion 1.3.2 --dataSize 0x00000000 --icon 0100000000ffffff00ffffffffffff1ffc0ff80fe107c0078003f003f807f81ffc3ffcfffcffffffff`
 
Error: 
`sha256.update(struct.pack('>I', targetId) + bytes(targetVersion, 'utf-8'))
TypeError: encoding without a string `argument``

I don't see any examples of setting the --targetVersion parameter. It seems to work for most people without? Not sure what's going on here.

**Comment by TamtamHero** [comment]
If you're using py2, please start using py3. This is probably the cause of this error, and we don't support py2 anymore.

**Comment by mattspaeth** [comment]
I'm using WinPython 3.6.6

**Comment by TamtamHero** [comment]
I can't reproduce it with python 3.6.7 on Linux. Are you sure that your ledgerblue package is up to date ? Current version is 0.1.23, you can fetch it with `pip show ledgerblue`.

**Comment by mattspaeth** [comment]
That was it. Upgrading to 0.1.23 fixed it. Thank you.

**Comment by chrisbward** [comment]
```
pip show ledgerblue
Name: ledgerblue
Version: 0.1.32
Summary: Python library to communicate with Ledger Blue/Nano S
Home-page: https://github.com/LedgerHQ/blue-loader-python
Author: Ledger
Author-email: hello@ledger.fr
License: UNKNOWN
Location: /home/developer/Tools/ledger/blue-loader-python/ledger/lib/python3.8/site-packages
Requires: hidapi, ecpy, python-u2flib-host, protobuf, pycryptodomex, pillow, future, websocket-client
Required-by: 
```

issue still occurs!
```
python --version
Python 3.8.2
```
