### ISSUE TITLE
Unable to sideload app on Nano X

### ISSUE THREAD

**Issue by Kryptoxic** [LedgerHQ/blue-loader-python#68]
Hi, I have recently gotten a Nano X for the purpose of testing my apps on the Nano X, however, when I try to sideload an app which I coded, I keep getting a "Invalid status 69d5 (Unknown reason)". Has the ledgerblue module been updated to support the Nano X yet?

**Comment by justinvforvendetta** [comment]
@Kryptoxic welcome to the club

**Comment by saberShenFeng** [comment]
did you fixed it？ i get the same trouble.

**Comment by saberShenFeng** [comment]
> did you fixed it？ i get the same trouble.

![屏幕快照 2019-12-05 下午4 57 42](https://user-images.githubusercontent.com/16433127/70219787-67073600-1780-11ea-9ac5-0ddd3896067e.png)

**Comment by Kryptoxic** [comment]
Nope. It's ledger's end. The firmware on the Nano X does not support sideloading of unsigned apps apparently. We'll need to wait for a newer firmware that allows unsigned apps to be sideloaded.

**Comment by justinvforvendetta** [comment]
yeah we just have to wait.

**Comment by RainbowMiner** [comment]
Still waiting for a fix. I'ld love to sideload the Swap app, finally.

**Comment by RainbowMiner** [comment]
@saberShenFeng  try the following to check if your device is genuine:
```
python -m ledgerblue.checkGenuineRemote --targetId 0x33000004
```

**Comment by wylie39** [comment]
Any news?

**Comment by TamtamHero** [comment]
Unlike on the nano S, where you can load whatever your want on a device from retail, the nano X is locked for the time being.
You should request a developer Nano X on our developer slack (http://ledger-dev.slack.com/, contact our support to get access to it), and contact @FabriceDautriat there to get one.
It's not a practical situation for you nor for us, but that's how it is for now and we haven't figured out a way to solve this yet :grimacing:

**Comment by dzid26** [comment]
Just for google to index this.. - when I tried to sideload something on Nano X, I got the following error code nowadays:
TransportStatusError: Ledger device: UNKNOWN_ERROR (0x6805)
