### ISSUE TITLE
Installation instructions for Mac

### ISSUE THREAD

**Issue by Pet3ris** [LedgerHQ/blue-loader-python#80]
Hi There,

I tried to use this app with the following dependencies:

```bash
brew install libtool
brew install libusb
brew install libusb-compat
```

But it's not able to connect to Ledger Nano X "OSError: open failed". Are there any other dependencies that are needed to use this library?

**Comment by TamtamHero** [comment]
Hello :wave: 
MacOS is not supported, you should instead use a docker image to build (https://github.com/LedgerHQ/ledger-app-builder) and a Linux VM to load the app on your device.
