### ISSUE TITLE
Cannot sideload on the Nano X even with the SDK now public

### ISSUE THREAD

**Issue by qtum-neil** [LedgerHQ/blue-loader-python#82]
With the recent release of the long awaited Nano X SDK: https://github.com/LedgerHQ/nanox-secure-sdk

It seems it's still impossible to load apps on the Nano X, still getting the same error:

`Invalid status 69d5 (Unknown reason)`

Would be great to add support for the Nano X.

Thanks!

**Comment by TamtamHero** [comment]
Sideloading on Nano X is still disabled, sorry !
We released the SDK so you can compile apps for the Ledger emulator, Speculos: https://github.com/LedgerHQ/speculos
