### ISSUE TITLE
Invalid status 69d5 (Unknown reason)

### ISSUE THREAD

**Issue by TrAyZeN** [LedgerHQ/blue-loader-python#86]
Hi,
I am trying to load the [app boilerplate](https://github.com/ledgerHQ/app-boilerplate) on a Nano X.
The development environment was setup using the `setup-env` script from https://developers.ledger.com/docs/nano-app/quickstart.
When I load the app using `make load`, it fails with the following backtrace:
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/user/.local/lib/python3.8/site-packages/ledgerblue/loadApp.py", line 204, in <module>
    secret = getDeployedSecretV2(dongle, bytearray.fromhex(args.rootPrivateKey), args.targetId)
  File "/home/user/.local/lib/python3.8/site-packages/ledgerblue/deployed.py", line 115, in getDeployedSecretV2
    dongle.exchange(apdu)
  File "/home/user/.local/lib/python3.8/site-packages/ledgerblue/comm.py", line 145, in exchange
    raise CommException("Invalid status %04x (%s)" % (sw, possibleCause), sw, response)
ledgerblue.commException.CommException: Exception : Invalid status 69d5 (Unknown reason)
```

**Comment by tjanez** [comment]
See also #58.

**Comment by angrywasp** [comment]
Looks to me like ledger don't actually care about developers building apps for this device. Readme says the X is supported when clearly it isn't and the ledger team couldn't even be bothered to respond to ther numerous issues raised over it. Really disappointing

**Comment by btchip** [comment]
Sorry about that, only special developer Nano X units are supported. You can debug your application with Speculos (https://github.com/LedgerHQ/speculos) as described on our Developer Portal (https://developers.ledger.com/)
